[workspace]
members = [
    "mopro-ffi",
    "test-e2e",
    "cli",
    "mopro-wasm",
    "test-e2e/mopro-wasm-lib",
    "circom-prover",
]
resolver = "2"
exclude = ["mopro-example-app"]

[workspace.dependencies]
rust-witness = "0.1"

uniffi = { version = "=0.29.0" }
