[package]
name = "test-e2e"
version = "0.1.0"
edition = "2021"

[lib]
name = "mopro_bindings"
crate-type = ["lib", "cdylib", "staticlib"]

[[bin]]
name = "ios"

[[bin]]
name = "android"

[[bin]]
name = "web"

[dependencies]
mopro-ffi = { path = "../mopro-ffi", features = ["halo2", "circom", "rapidsnark", "witnesscalc"] }
mopro-wasm = { path = "../mopro-wasm" }
uniffi = { workspace = true } 

# Circom dependencies
rust-witness = "0.1"
witnesscalc-adapter = { git = "https://github.com/zkmopro/witnesscalc_adapter.git", branch = "dylib" }
anyhow = "1.0.74"
num-bigint = { version = "0.4.0" }

# Halo2 dependencies
halo2-keccak-256 = { git = "https://github.com/ElusAegis/halo2-keccak-stable.git" }
plonk-fibonacci = { workspace = true }
hyperplonk-fibonacci = { workspace = true }
gemini-fibonacci = { workspace = true }
thiserror = "=2.0.3"
circom-prover = { version = "0.1.0", path = "../circom-prover" }

[build-dependencies]
mopro-ffi = { path = "../mopro-ffi", features = ["rapidsnark", "witnesscalc"] }
uniffi = { workspace = true, features = ["build"] }

# Circom dependencies
rust-witness = "0.1"
witnesscalc-adapter = { git = "https://github.com/zkmopro/witnesscalc_adapter.git", branch = "dylib" }

# remove after uniffi is upgraded (see https://github.com/mozilla/uniffi-rs/issues/2346)
[lints.clippy]
empty-line-after-doc-comments = "allow"

[dev-dependencies]
uniffi = {  workspace = true, features = ["bindgen-tests"] }

